file_format: "1"
id: corne
name: Corne
type: shield
url: https://github.com/foostan/crkbd/
requires: [xiao_d]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
siblings:
  - corne_left
  - corne_right
  - corne_dongle
  - corne_peripheral_left 